"""Seed data generated from bakery_catalog.html."""

CATEGORY_NAMES = [
    'Biscuits, Cookies & Crackers',
    'Bread & Rolls',
    'Cakes & Cupcakes',
    'Drinks & Beverages',
    'Frozen / Specialty Doughs',
    'Laminated & Puff Pastries',
    'Pies & Tarts',
    'Savory Snacks',
]

FEATURED_PRODUCT_NAMES = [
    'Classic White Sandwich Loaf',
    'Butter Croissant',
    'Chocolate Fudge Cake (whole)',
    'Chocolate Chip Cookies (pack of 6)',
    'Apple Pie (whole)',
    'Margherita Pizza Slice',
]

CATALOG_PRODUCTS = [
    {
        'category': 'Bread & Rolls',
        'name': 'Classic White Sandwich Loaf',
        'price': '35.00',
        'description': 'A soft, pillowy loaf baked with enriched white flour, producing a fine, even crumb ideal for everyday sandwiches and toast. The crust is thin and golden, achieved through steam baking in the final minutes of the bake. Its mild, slightly sweet flavor pairs with virtually any spread, filling, or topping. Made fresh daily with no preservatives, it is best consumed within three days of purchase.',
    },
    {
        'category': 'Bread & Rolls',
        'name': 'Sourdough Boule',
        'price': '65.00',
        'description': 'A round, rustic sourdough loaf built on a live fermented starter that gives it its signature tang and complex depth of flavor. The long, slow fermentation - typically 12 to 18 hours - develops an open, irregular crumb structure and a thick, crackly crust. Its natural acidity not only enhances taste but also extends shelf life compared to commercial yeast breads. Best enjoyed sliced thick with good butter, aged cheese, or a hearty soup.',
    },
    {
        'category': 'Bread & Rolls',
        'name': 'French Baguette',
        'price': '30.00',
        'description': 'A long, slender French classic with a crisp, deeply caramelized crust and a light, airy interior full of irregular holes. Made from a simple dough of flour, water, salt, and a small amount of yeast, it relies entirely on technique - proper shaping, slashing, and steam injection - for its texture and crust color. The baguette is at its absolute best within two hours of baking, when the crust is still crackling. It is the backbone of a good cheese board, bruschetta, or a simple beurre sandwich.',
    },
    {
        'category': 'Bread & Rolls',
        'name': 'Whole Wheat Loaf',
        'price': '40.00',
        'description': 'A dense, nutritious loaf made with 100% whole wheat flour, retaining all the bran and germ that white flour processing removes. It carries a subtly nutty, earthy flavor that becomes richer when toasted, and the texture is slightly denser with a tighter crumb than white bread. High in dietary fiber and complex carbohydrates, it makes for a genuinely filling and health-conscious choice. A perfect everyday loaf for those watching their diet without sacrificing the comfort of fresh-baked bread.',
    },
    {
        'category': 'Bread & Rolls',
        'name': 'Rye Bread',
        'price': '55.00',
        'description': "A hearty, deeply flavored loaf baked with a substantial portion of rye flour, which gives it a distinctively dense crumb and a dark, earthy appearance. Rye's lower gluten content produces a moister, more compact loaf compared to wheat breads, and the flavor carries notes of mild sourness, especially when made with a rye sourdough starter. It pairs exceptionally well with smoked fish, cold cuts, strong mustards, and sharp cheeses. A staple in Northern European baking traditions with a remarkably long shelf life.",
    },
    {
        'category': 'Bread & Rolls',
        'name': 'Brioche Loaf',
        'price': '70.00',
        'description': 'A luxuriously enriched French bread made with a high ratio of butter and eggs, giving it a tender, feathery crumb and a rich, golden-yellow interior. The dough requires extended kneading and a long, cold overnight proof to develop both structure and depth of flavor. Its mildly sweet, buttery taste makes it exceptional for French toast, bread pudding, or eaten simply with a light dusting of powdered sugar. The glossy, deep-brown crust achieved through an egg wash gives it an unmistakably elegant appearance.',
    },
    {
        'category': 'Bread & Rolls',
        'name': 'Dinner Rolls (6-pack)',
        'price': '45.00',
        'description': 'Soft, pillowy pull-apart rolls baked in a cluster, brushed with melted butter the moment they exit the oven for a glistening finish and extra richness. Each roll has a whisper-thin crust that gives way to a cloud-soft, slightly elastic interior perfect for mopping up sauces or pairing with soups and stews. Made with an enriched dough of milk, butter, and a touch of sugar, they carry a gentle, milky sweetness. They reheat exceptionally well and make a crowd-pleasing addition to any dinner table.',
    },
    {
        'category': 'Bread & Rolls',
        'name': 'Multigrain Seeded Bread',
        'price': '60.00',
        'description': 'A robust, wholesome loaf packed with a blend of seeds - sunflower, sesame, flaxseed, and pumpkin - along with multiple grain flours for a nutty, complex flavor profile. Every slice is generously studded with seeds, adding crunch, texture, and a significant nutritional boost including healthy fats, protein, and omega-3 fatty acids. The crumb is moist and slightly dense with a satisfying chew, while the crust bakes firm and deeply golden. This is the bread for people who want substance and character in every bite.',
    },
    {
        'category': 'Laminated & Puff Pastries',
        'name': 'Butter Croissant',
        'price': '25.00',
        'description': 'The gold standard of laminated pastry - a crescent-shaped marvel built from hundreds of alternating layers of dough and cold European-style butter. The lamination process creates the signature honeycomb interior and shatteringly flaky exterior, and each bite releases steam and shatters into buttery, golden flakes. Proper croissant-making is a two-day process that cannot be rushed, and the result is one of the most satisfying things in all of baking. Best eaten warm, within an hour of coming out of the oven.',
    },
    {
        'category': 'Laminated & Puff Pastries',
        'name': 'Almond Croissant',
        'price': '35.00',
        'description': 'A twice-baked indulgence made by soaking a day-old croissant in rum-spiked simple syrup, filling it generously with almond cream (frangipane), and topping with sliced almonds before a second bake. The result is a pastry that is simultaneously crisp on the outside, intensely moist and custardy inside, and fragrant with roasted almond. The frangipane is made from butter, sugar, eggs, and almond flour - rich, dense, and deeply nutty. This is the most decadent member of the croissant family and worth every cedi.',
    },
    {
        'category': 'Laminated & Puff Pastries',
        'name': 'Danish Pastry',
        'price': '30.00',
        'description': 'A yeasted laminated pastry shaped into spirals, pinwheels, or envelopes and filled with custard cream, fruit compote, or sweet cheese. The dough is richer than a croissant dough, with additional eggs and higher sugar content, resulting in a more tender, bread-like crumb beneath the flaky layers. The glaze of apricot jam and a drizzle of fondant icing gives each piece a polished, bakery-window look. Danishes are best eaten warm, when the filling is still soft and the pastry layers are at their most delicate.',
    },
    {
        'category': 'Laminated & Puff Pastries',
        'name': 'Puff Pastry Sausage Roll',
        'price': '25.00',
        'description': 'A golden, flaky puff pastry case wrapped tightly around a well-seasoned sausage or spiced minced meat filling, then baked until the pastry is deeply bronzed and the layers are fully separated. The contrast between the shatteringly crisp, buttery pastry and the savory, juicy filling is what makes the sausage roll universally loved. Seasoning typically includes herbs, garlic, onion, and a hint of mustard mixed into the meat. Served hot or at room temperature, it is the perfect grab-and-go savory snack.',
    },
    {
        'category': 'Laminated & Puff Pastries',
        'name': 'Apple Strudel (slice)',
        'price': '40.00',
        'description': 'A classic Central European pastry of wafer-thin layers of stretched dough rolled around a fragrant filling of spiced apple, raisins, cinnamon, and breadcrumbs soaked in brown butter. The dough, stretched until nearly translucent, bakes into a gossamer-crisp shell that shatters at the touch of a fork to reveal the steam-soft, cinnamon-scented filling within. A generous dusting of powdered sugar finishes each slice. Served warm alongside a spoonful of whipped cream or vanilla custard, it is the quintessential autumn pastry.',
    },
    {
        'category': 'Laminated & Puff Pastries',
        'name': 'Baklava (piece)',
        'price': '20.00',
        'description': 'A rich, jewel-like pastry of Middle Eastern and Mediterranean origin, built from dozens of layers of thin phyllo dough alternating with a sweetened, spiced mixture of finely chopped pistachios, walnuts, or almonds. After baking until crisp and golden, the entire tray is immediately soaked in a fragrant syrup of honey, rosewater, and lemon juice, which seeps into every layer. The result is intensely sweet, sticky, crunchy, and aromatic. Each diamond-cut piece is a labor of love and tradition that rewards patience.',
    },
    {
        'category': 'Laminated & Puff Pastries',
        'name': 'Palmier (Elephant Ear)',
        'price': '15.00',
        'description': 'A deceptively simple French pastry made from just two ingredients - puff pastry and sugar - rolled, folded symmetrically, and sliced into delicate heart-shaped biscuits. During baking, the sugar caramelizes on contact with the hot oven floor, creating a crackly, amber glaze on both flat sides while the interior remains flaky and tender. They are crisp, sweet, and utterly addictive, with a satisfying snap when broken in half. Palmiers are proof that the most elegant things in baking often require the fewest ingredients.',
    },
    {
        'category': 'Cakes & Cupcakes',
        'name': 'Victoria Sponge Cake (whole)',
        'price': '250.00',
        'description': 'The quintessential British celebration cake - two layers of light, even-crumbed sponge sandwiched with strawberry jam and freshly whipped cream, finished with a dusting of icing sugar. The sponge is made using the classic creaming method, incorporating air into the butter and sugar to produce a batter that bakes up delicately tender and never dense. Its simplicity is its greatest strength - no elaborate frosting or decoration, just pristine, honest baking technique on full display. A must for afternoon tea.',
    },
    {
        'category': 'Cakes & Cupcakes',
        'name': 'Chocolate Fudge Cake (whole)',
        'price': '280.00',
        'description': 'A deeply intense, three-layer chocolate cake made with Dutch-process cocoa and melted dark chocolate in the batter, resulting in a dense but supremely moist crumb. Each layer is frosted with a glossy, ganache-based chocolate fudge icing that sets into a rich, silky coat. A touch of hot coffee in the batter amplifies the cocoa depth without making the cake taste of coffee - a trick used by professional bakers. This is the cake for genuine chocolate lovers: not sweet for the sake of it, but complex, dark, and satisfying.',
    },
    {
        'category': 'Cakes & Cupcakes',
        'name': 'Red Velvet Cake (whole)',
        'price': '300.00',
        'description': "A striking, vibrant-crimson layer cake with a delicate, velvety crumb that earns its name from the reaction between natural cocoa and acidic buttermilk, which gives the cake its characteristic soft texture. Traditionally paired with a tangy cream cheese frosting, the combination balances the cake's mild sweetness with a pleasant sharpness. The visual drama of red layers against white frosting makes it one of the most photogenic cakes in the bakery. It is as crowd-pleasing at birthdays and celebrations as it is aesthetically bold.",
    },
    {
        'category': 'Cakes & Cupcakes',
        'name': 'Carrot Cake (whole)',
        'price': '260.00',
        'description': 'A moist, spice-forward cake loaded with freshly grated carrots, toasted walnuts, and warm spices - cinnamon, nutmeg, ginger - bound together by a light vegetable oil batter that guarantees exceptional moistness. The natural sugars from the carrots caramelize subtly during baking, adding depth and a hint of earthiness to the overall flavor. A thick, swooping coat of cream cheese frosting provides the ideal rich, tangy counterpoint to the warmly spiced cake. One of the rare cakes that actually tastes better on the second day as the spices develop.',
    },
    {
        'category': 'Cakes & Cupcakes',
        'name': 'Vanilla Cupcake',
        'price': '20.00',
        'description': 'A perfectly proportioned individual cake made from a classic vanilla sponge batter and crowned with a generous swirl of vanilla buttercream piped into a tall, dramatic peak. The cupcake sponge is tender and fragrant with real vanilla bean, producing a delicate flavor that the best-quality butter buttercream complements rather than overwhelms. The buttercream is whipped until extraordinarily light and silky, achieving a texture that melts on the tongue rather than sitting heavy. Available in custom colors and designs for events, birthdays, and parties.',
    },
    {
        'category': 'Cakes & Cupcakes',
        'name': 'Lemon Drizzle Cake (loaf)',
        'price': '150.00',
        'description': 'A bright, sunny loaf cake made with fresh lemon zest folded directly into the batter, which bakes into a golden, tender crumb bursting with natural citrus fragrance. Immediately after coming out of the oven, it receives a generous dousing of lemon sugar syrup that soaks into the still-warm cake, creating a gloriously moist interior with a slightly crystallized, crunchy top. The final drizzle of lemon icing adds a sharp, clean sweetness that makes every slice feel refreshing. The perfect companion to afternoon tea or coffee.',
    },
    {
        'category': 'Cakes & Cupcakes',
        'name': 'Pound Cake (loaf)',
        'price': '120.00',
        'description': "Named for its original recipe - one pound each of butter, sugar, eggs, and flour - the pound cake is one of the oldest and most reliable bakes in the Western tradition. The result is a dense, buttery, fine-crumbed loaf with a firm yet moist texture that holds up well for several days without drying out. Its restraint is its virtue: the flavor is pure, clean butter and vanilla, a canvas that pairs equally well with fresh fruit, whipped cream, or simply on its own. A baker's benchmark cake.",
    },
    {
        'category': 'Cakes & Cupcakes',
        'name': 'Marble Cake (whole)',
        'price': '230.00',
        'description': 'A visually captivating round cake created by swirling vanilla and chocolate batters together in a single tin before baking, producing a distinctive marbled cross-section that is different with every slice. The two batters are made from the same base for a seamless, tender texture, ensuring neither flavor dominates but both remain clearly distinct. Covered in a smooth chocolate ganache glaze that sets into a mirror-like finish, it is as handsome to look at as it is to eat. An enduring family favorite that appeals to both chocolate and vanilla partisans.',
    },
    {
        'category': 'Biscuits, Cookies & Crackers',
        'name': 'Butter Cookies (pack of 10)',
        'price': '35.00',
        'description': 'Classic piped or stamped shortbread-style cookies made with a high ratio of quality butter, resulting in a melt-in-the-mouth texture that practically dissolves on the tongue. The dough uses a combination of icing sugar and regular sugar to achieve a fine, tender crumb rather than a crunchy bite, and real butter - never margarine - is non-negotiable for the depth of flavor. Some varieties are half-dipped in tempered dark chocolate for contrast. They are elegant, simple, and the kind of cookie that disappears from a tin long before you expect them to.',
    },
    {
        'category': 'Biscuits, Cookies & Crackers',
        'name': 'Shortbread Fingers (pack of 8)',
        'price': '30.00',
        'description': 'A Scottish classic made from just three ingredients - butter, plain flour, and sugar - in exact proportions that produce a crumbly, sandy, incredibly rich biscuit. The dough is worked as little as possible to avoid developing gluten, so shortbread crumbles at a gentle squeeze rather than snapping. The characteristic pale golden color and faint ridged edges from a fork are marks of an authentic, properly made shortbread. They are deeply buttery, subtly sweet, and so rich that two fingers with a cup of tea is often all you need.',
    },
    {
        'category': 'Biscuits, Cookies & Crackers',
        'name': 'Chocolate Chip Cookies (pack of 6)',
        'price': '40.00',
        'description': 'A benchmark American-style cookie - large, golden-edged, and loaded with semi-sweet chocolate chunks - baked to a point where the edges are set and lightly crisp while the center remains soft, fudgy, and just barely underbaked. Brown butter in the dough adds a deep, nutty, almost caramel complexity beyond what standard creamed-butter cookies achieve. A critical touch of flaky sea salt on top before baking brings out both the sweetness and the chocolate in a way that changes everything. Intentionally thick and generous - a cookie that means business.',
    },
    {
        'category': 'Biscuits, Cookies & Crackers',
        'name': 'Ginger Snaps (pack of 10)',
        'price': '25.00',
        'description': 'Thin, circular cookies with a satisfying, brittle snap and a fiery kick of ground ginger, warm cinnamon, and a hint of clove baked into every bite. The crispness comes from a relatively low-moisture dough and a thorough bake that drives out almost all residual water, leaving behind a dense, intensely flavored biscuit that lingers on the palate. They are wonderful crumbled as a base for cheesecakes and tarts, dunked in tea or coffee, or simply eaten by the handful. A warming, spiced biscuit with real personality.',
    },
    {
        'category': 'Biscuits, Cookies & Crackers',
        'name': 'Savory Cheese Crackers (pack)',
        'price': '30.00',
        'description': 'Thin, crisp, lightly salted crackers made with sharp cheddar cheese folded directly into the dough, giving them an intensely savory, umami-rich character that sets them apart from plain water crackers. They bake up with a beautiful golden hue from the cheese and a texture that shatters cleanly without crumbling into dust. The seasoning includes a touch of paprika and dried herbs for added complexity. They are exceptional on a cheese board, paired with pate, or simply eaten on their own as a satisfying snack that does not pretend to be something healthier than it is.',
    },
    {
        'category': 'Biscuits, Cookies & Crackers',
        'name': 'Wafer Biscuits (pack)',
        'price': '20.00',
        'description': 'Layers of airy, paper-thin baked wafer sheets sandwiched together with a smooth, sweetened filling - classically vanilla or chocolate cream - pressed and sliced into neat rectangles. The wafer sheets are made from a very thin batter baked between heated plates, emerging crisp and almost weightless, creating that distinctive combination of delicate crunch and creamy richness. They are light, snackable, and never overly filling, making them the perfect accompaniment to a mid-morning coffee or afternoon tea. Popular with all ages.',
    },
    {
        'category': 'Biscuits, Cookies & Crackers',
        'name': 'Oatmeal Raisin Cookies (pack of 6)',
        'price': '35.00',
        'description': 'A chewy, hearty cookie built on rolled oats that give it a rustic, substantial texture quite unlike a standard flour-based biscuit. The oats toast slightly during baking, adding a gentle nuttiness that pairs beautifully with the plump, hydrated raisins and warm spices - cinnamon and a small amount of nutmeg - folded through the dough. They are sweet but not cloying, with enough textural complexity from the oat clusters to make each bite interesting. Widely regarded as the most underrated cookie, these are wholesome without sacrificing indulgence.',
    },
    {
        'category': 'Pies & Tarts',
        'name': 'Apple Pie (whole)',
        'price': '180.00',
        'description': 'A deep-dish, double-crusted classic filled with layers of thinly sliced, cinnamon-spiced apples tossed with sugar, lemon juice, and a touch of cornstarch for a filling that is juicy but never soupy. The all-butter crust is made with cold butter cut into the flour to create distinct, visible layers that bake up flaky and golden, with a lattice top crust vented to release steam. Brushed with egg wash and finished with a sprinkle of raw sugar for a glistening, slightly crunchy lid. Served warm with a scoop of vanilla ice cream, it is perfect.',
    },
    {
        'category': 'Pies & Tarts',
        'name': 'Egg Custard Tart',
        'price': '25.00',
        'description': 'A silky-smooth egg custard poured into a blind-baked shortcrust pastry shell and gently baked until just barely set - wobbly at the center when removed from the oven, firming to a perfect trembling consistency as it cools. The custard is made with egg yolks, double cream, whole milk, and a subtle flavoring of freshly grated nutmeg over the top before baking. The contrast between the crisp, buttery pastry and the yielding, creamy filling is one of the most satisfying textural experiences in all of dessert baking. Simple, classic, and endlessly comforting.',
    },
    {
        'category': 'Pies & Tarts',
        'name': 'Lemon Meringue Tart',
        'price': '35.00',
        'description': "A stunning tart built in three distinct layers: a blind-baked sweet pastry shell, a brilliantly tart lemon curd filling set to a glossy sliceable consistency, and a towering cloud of Italian meringue torched to golden peaks. The lemon curd is made with fresh juice and zest, egg yolks, and butter, cooked slowly for a vibrant, intensely citrus flavor that cuts through the meringue's sweetness beautifully. Each element is made from scratch and assembled to order. It is technically demanding, visually dramatic, and entirely worth the effort.",
    },
    {
        'category': 'Pies & Tarts',
        'name': 'Meat Pie',
        'price': '30.00',
        'description': 'A beloved, handheld savory pie with a golden shortcrust pastry case encasing a well-seasoned filling of minced beef, diced onion, garlic, tomato, and herbs - slow-cooked until deeply flavorful and slightly thickened with stock. The pastry is sturdy enough to hold its shape when picked up but shatters satisfyingly when bitten. Brushed with egg wash for a deep golden finish, it is baked until the crust is fully cooked through with no raw dough beneath the filling. A staple of Ghanaian bakeries and an institution at every roadside shop.',
    },
    {
        'category': 'Pies & Tarts',
        'name': 'Strawberry Jam Tart',
        'price': '20.00',
        'description': 'A simple, cheerful tart made from a crisp, buttery shortcrust pastry base filled with a glossy pool of high-fruit-content strawberry jam, finished with a decorative lattice of pastry strips. The tart case is blind-baked first to ensure a fully cooked, crisp base before the jam is added, preventing the dreaded soggy-bottom situation that undermines lesser tarts. The jam bubbles and sets during the second bake, concentrating the fruit flavor and creating a jammy, slightly chewy filling that contrasts beautifully with the buttery pastry. Nostalgic, unpretentious, and delightful.',
    },
    {
        'category': 'Pies & Tarts',
        'name': 'Chocolate Ganache Tart',
        'price': '40.00',
        'description': 'An elegant patisserie-style dessert built on a crisp, deep-colored cocoa shortcrust base filled with a thick, shiny ganache made from the finest dark chocolate and heavy cream in equal proportions. The ganache is poured while warm and allowed to set at room temperature into a surface as smooth and reflective as polished stone. A few flakes of fleur de sel and a dusting of cocoa powder are the only decoration - no more is needed. Cutting through the clean, sharp edge of the set ganache to reveal the perfectly dark, glossy interior is one of the quiet genuine pleasures of patisserie.',
    },
    {
        'category': 'Savory Snacks',
        'name': 'Margherita Pizza Slice',
        'price': '35.00',
        'description': "A single, generous slice from a 12-inch Neapolitan-style pizza baked at high heat on a stone surface to achieve leopard-spotting on the crust's underside and the characteristic charred, puffy cornicione (edge). The tomato sauce is made from crushed San Marzano-style tomatoes, seasoned only with salt and fresh basil - no sugar, no oregano. Fresh mozzarella is torn rather than grated and placed over the sauce, melting into pools of milky white against the red. Finished with fresh basil and a drizzle of olive oil after the bake.",
    },
    {
        'category': 'Savory Snacks',
        'name': 'Pinsa Romana',
        'price': '80.00',
        'description': 'An ancient Roman flatbread enjoying a well-deserved modern renaissance, distinguished from standard pizza by its oval shape, its highly hydrated dough (often 80% water content), and the use of a blend of wheat, soy, and rice flours that produces a remarkably light, airy crumb beneath a crispy, cracker-like base. The long cold fermentation - a minimum of 24 hours - develops exceptional flavor and a texture that remains pleasantly crisp without becoming tough. Topped simply with burrata, prosciutto, and rocket, or classically with tomato and mozzarella.',
    },
    {
        'category': 'Savory Snacks',
        'name': 'Focaccia with Rosemary',
        'price': '55.00',
        'description': 'A thick, pillowy Ligurian flatbread made with an olive-oil-enriched, highly hydrated dough proofed in a well-oiled baking tray, dimpled deeply by hand, then drizzled with a brine of olive oil, water, and coarse salt before baking. The oil works into the dimples and fries the underside of the bread as it bakes, creating a shatteringly crisp bottom and a golden, chewy top studded with fresh rosemary sprigs. The crumb is open, springy, and tender - almost custardy in the best examples. Equal parts bread and olive oil delivery vehicle.',
    },
    {
        'category': 'Savory Snacks',
        'name': 'Soft Pretzels',
        'price': '30.00',
        'description': 'A dense, chewy, braided dough rope shaped into the classic knot form and briefly dipped in a baked baking soda solution - an approximation of the alkaline lye bath that gives authentic German pretzels their distinctive dark mahogany crust and unique chewiness. After the alkaline bath, the pretzels are dusted with coarse pretzel salt and baked until deeply browned and glossy. Inside, the crumb is dense and slightly doughy in the best possible way. Best eaten warm, pulled apart by hand, and dipped in whole-grain mustard or beer cheese.',
    },
    {
        'category': 'Savory Snacks',
        'name': 'Hot Bread Rolls (3-pack)',
        'price': '25.00',
        'description': 'Three soft, individual bread rolls pulled fresh from the oven, with a thin, slightly crisp crust that gives way immediately to a pillowy, steam-filled interior. Made from a simple enriched dough of flour, yeast, salt, milk, and a small amount of butter for tenderness, they are shaped tightly to ensure an even rise and a smooth, rounded top. Baked closely together in the pan so they rise against each other, producing soft, tear-apart sides even fluffier than the outer crust. The simplest, most honest bakery product on this list.',
    },
    {
        'category': 'Savory Snacks',
        'name': 'Garlic Breadsticks (6-pack)',
        'price': '30.00',
        'description': 'Long, slender bread sticks made from a simple yeasted dough twisted into thin ropes, brushed liberally with a compound butter of roasted garlic, fresh parsley, and a touch of chili flake before baking until crisp on the outside and just slightly soft at the very center. The garlic is roasted rather than raw to soften its sharpness into a sweet, mellow depth that permeates every centimeter of the breadstick. They pull apart satisfyingly and leave a lasting fragrance. An ideal side for pasta, soups, or antipasto platters.',
    },
    {
        'category': 'Savory Snacks',
        'name': 'Cheesy Flatbread',
        'price': '45.00',
        'description': "A thin, oval flatbread baked directly on a stone to achieve a cracker-like crispness on the base, topped with a generous layer of melted mozzarella and aged cheddar that browns and bubbles in the oven's heat into golden, lacy patches. A drizzle of honey and a scattering of fresh thyme leaves added after baking creates a savory-sweet contrast that elevates the flatbread well beyond simple cheese on bread. The edges are thin and cracker-crisp while the center retains just enough bread substance to hold the cheese without going soggy.",
    },
    {
        'category': 'Frozen / Specialty Doughs',
        'name': 'Frozen Croissant Dough (6-pack)',
        'price': '85.00',
        'description': 'Pre-laminated, individually shaped croissant doughs that have been taken through all the technical steps of butter lamination by professional bakers, then flash-frozen at the raw stage before the final proof. Home bakers or small cafe operators simply remove them from the freezer the night before, allow them to proof slowly in the refrigerator overnight, and bake fresh the next morning. The quality of the lamination is indistinguishable from scratch-made. Convenience without compromise - exactly what frozen specialty dough should be.',
    },
    {
        'category': 'Frozen / Specialty Doughs',
        'name': 'Pre-proofed Dinner Rolls (8-pack)',
        'price': '70.00',
        'description': 'Eight individually shaped dinner rolls taken through a complete first rise and shaped by professional bakers, then frozen at the critical moment just before their final proof. To bake, they simply need to be arranged in a pan and left to thaw and complete their final proof at room temperature, then baked directly. The result is indistinguishable from freshly made scratch rolls with none of the timing pressure. Ideal for restaurants, caterers, and households that want fresh-baked bread without managing yeast or dough from scratch.',
    },
    {
        'category': 'Frozen / Specialty Doughs',
        'name': 'Ready-to-Bake Pizza Dough',
        'price': '55.00',
        'description': 'A professionally made, long-fermented pizza dough ball that has been cold-proofed for 24 to 48 hours by trained bakers to develop the complex flavors and extensibility that distinguish great pizza from mediocre pizza. Packaged and chilled for immediate refrigerator storage, it simply needs to be brought to room temperature for an hour before stretching and topping. The dough uses a blend of 00 flour and high-gluten bread flour for the ideal balance of tenderness and chew. One ball makes a generous 12-inch pizza.',
    },
    {
        'category': 'Frozen / Specialty Doughs',
        'name': 'Frozen Cinnamon Roll Dough (6-pack)',
        'price': '90.00',
        'description': 'Six generously sized cinnamon rolls pre-shaped with a swirl of brown butter, cinnamon, and brown sugar filling locked between the layers of an enriched brioche-style dough, frozen before the final proof. The night before serving, they are placed in a buttered baking dish to thaw and complete their proof in the refrigerator; by morning, they have puffed beautifully and are ready to bake. Each pack comes with a sachet of cream cheese frosting to be spread over the rolls fresh from the oven while still hot. The smell alone is worth the purchase.',
    },
    {
        'category': 'Frozen / Specialty Doughs',
        'name': 'Pre-made Pie Crust Shells (2-pack)',
        'price': '60.00',
        'description': 'Two professionally blind-baked, fully cooked all-butter shortcrust pastry shells in standard 9-inch tart tins, ready to be filled with any sweet or savory filling without further baking of the case. Made with cold butter rubbed into flour with a touch of icing sugar, baked with weights to prevent shrinkage, and finished until fully cooked through with no raw dough taste. An excellent time-saving product for home cooks and professional kitchens alike - the most tedious part of tart-making done perfectly, every time.',
    },
    {
        'category': 'Frozen / Specialty Doughs',
        'name': 'Frozen Brioche Dough (loaf)',
        'price': '75.00',
        'description': 'A single loaf of enriched, high-butter brioche dough that has been mixed and developed to the correct windowpane stage by professional bakers, shaped, and then frozen before its final proof. Simply remove from the freezer, allow to thaw overnight in the refrigerator, then let it complete its final room-temperature proof in the tin before baking. The result is a freshly baked brioche with the full depth of flavor from the cold fermentation - feathery interior, deep golden crust, unmistakable butter fragrance - without hours of kneading.',
    },
    {
        'category': 'Drinks & Beverages',
        'name': 'Espresso Shot',
        'price': '25.00',
        'description': 'A concentrated 30ml extraction of finely ground, freshly roasted coffee forced through by 9 bars of pressure from a professional espresso machine, producing a small, syrupy shot topped with a thick layer of reddish-brown crema. The crema - formed from emulsified coffee oils and CO2 released during extraction - carries the most volatile, fragrant aromatic compounds and is the hallmark of a well-pulled espresso. The flavor is bold, complex, and intense: bright and acidic in the top notes, bittersweet chocolate in the body, with a clean, lingering finish.',
    },
    {
        'category': 'Drinks & Beverages',
        'name': 'Cappuccino',
        'price': '45.00',
        'description': "A perfectly balanced Italian espresso drink built in equal thirds - espresso, steamed milk, and milk foam - served in a wide ceramic cup. The microfoam is produced by stretching and incorporating air into cold whole milk during steaming, creating a texture so smooth and dense that it holds its shape on the tongue. A properly made cappuccino is sweet without sugar, because the steaming process converts milk's lactose into sweeter compounds. It is the most technically demanding milk drink and the most rewarding when done right.",
    },
    {
        'category': 'Drinks & Beverages',
        'name': 'Caramel Latte',
        'price': '55.00',
        'description': "A sweet, indulgent espresso-milk drink made with a double shot of espresso, a generous pour of house-made salted caramel syrup, and a large volume of steamed whole milk, finished with a small amount of foam and a drizzle of caramel sauce on top. The caramel syrup is made in-house from butter, cream, brown sugar, and a pinch of sea salt - richer and less aggressively sweet than commercial syrups. The saltiness amplifies the coffee's depth without masking it. It is unabashedly a dessert drink and makes no apology for that.",
    },
    {
        'category': 'Drinks & Beverages',
        'name': 'Chai Tea Latte',
        'price': '45.00',
        'description': 'A warming, aromatic drink made from a concentrated brew of black tea steeped with whole spices - cinnamon, cardamom, ginger, cloves, and black pepper - combined with steamed whole milk for a creamy, deeply spiced beverage. The spice blend is brewed fresh daily rather than from a commercial syrup, resulting in a complexity absent from pre-made chai concentrates. The milk softens the tannins of the tea and rounds out the spices, producing a drink that is simultaneously warming, sweet, and complex. A superb cold-day drink.',
    },
    {
        'category': 'Drinks & Beverages',
        'name': 'Cold Brew Coffee',
        'price': '50.00',
        'description': "A smooth, naturally sweet cold coffee made by steeping coarsely ground, medium-roast coffee in cold filtered water for 18 to 24 hours at refrigerator temperature, then filtering slowly through paper to produce a crystal-clear, deeply concentrated extract. The cold brewing process extracts very different compounds from the coffee compared to hot methods, resulting in a drink remarkably low in bitterness and acidity while having exceptional depth of chocolate and caramel notes. Served over ice and diluted to the drinker's preferred strength. No heat, no shortcuts - just time.",
    },
    {
        'category': 'Drinks & Beverages',
        'name': 'Green Matcha Tea',
        'price': '50.00',
        'description': 'A vibrant, ceremonial-grade Japanese green tea powder whisked with hot (not boiling) water using a bamboo chasen to produce a thick, frothy, intensely vegetal and umami-rich tea. Served either traditionally as a pure whisked matcha or as a latte with steamed oat milk or whole milk. The quality of the matcha is everything - ceremonial-grade powder from shade-grown tea leaves has a vivid emerald color and a sweet, complex bitterness worlds away from the dull culinary-grade powders. A focused, clean caffeine hit without the anxious spike of espresso.',
    },
]
